#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

npm run test
CHANGED=$(git diff origin/main package.json | grep '"version":')
if [ -z "$CHANGED" ]; then
  echo "ERROR: You must update package.json version before pushing to main!"
  exit 1
fi
